---
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  # push: {branches: ["master", "main"]}
  push: {branches: ["stats"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Paris # Set timezone
          # achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B      # Display achievements with rank B or higher
          plugin_achievements_secrets: yes      # Display unlocked secrets achievements
          plugin_achievements_display: compact  # Use compact display
          plugin_achievements_limit: 0          # Display all unlocked achievements (no limit)
          plugin_achievements_ignored: octonaut # Hide "octonaut" achievement
          plugin_achievements_only: explorer    # Display only "explorer" achievement (don't use with "ignored" option)
          # notable
          plugin_notable: yes
          plugin_notable_filter: stars:>100 # Only display repositories with 500 stars or more (syntax based on GitHub search query)
          plugin_notable_from: organization # Only display contributions within organization repositories
          plugin_notable_repositories: yes  # Display repositories name instead of only organization name
          plugin_notable_indepth: yes       # Gather additional informations about contributions
          # isocalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
          # habits
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          # topics
          plugin_topics: yes
          plugin_topics_sort: stars    # Sort by most starred topics
          plugin_topics_mode: icons    # Display icons instead of labels
          plugin_topics_limit: 0       # Disable limitations
